name: Test Flask Trigger

on:
  workflow_dispatch:
    inputs:
      triggered_by:
        description: "GitHub user who triggered deployment"
        required: true
        type: string
      owner:
        description: "Repository owner or organization"
        required: true
        type: string
      repo:
        description: "Repository name"
        required: true
        type: string
      branch:
        description: "Branch name"
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print trigger details
        run: |
          echo "================================="
          echo "âœ… Hello from GitHub Actions"
          echo "Triggered by : ${{ github.event.inputs.triggered_by }}"
          echo "Owner        : ${{ github.event.inputs.owner }}"
          echo "Repository   : ${{ github.event.inputs.repo }}"
          echo "Branch       : ${{ github.event.inputs.branch }}"
          echo "================================="
